version: "3"

services:
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

  flask-app:
    build: .
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
