name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install project dependencies
        run: |
          python -m poetry install
      - name: Check flake8
        run: |
          poetry run flake8 .
      - name: Check bandit
        run: |
          poetry run bandit src/*.py
      - name: run Pytest
        run: |
          poetry run pytest
          poetry run pytest -s --cov=trdl --cov-append --cov-report=xml --cov-report term-missing tests
